### ISSUE TITLE
pip install error - simpleitk

### ISSUE THREAD

**Issue by jkim0731** [AllenInstitute/visual_behavior_glm#613]
While trying to install with editable mode in a new conda environment (python=3.7.9, Windows),
an error occurs when "Building wheel for simpleitk (PEP 517)".

Trying with pip version 21.2.2 gave the same error.

========================================================
Building wheels for collected packages: simpleitk
  Building wheel for simpleitk (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for simpleitk (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [543 lines of output]

**Comment by jkim0731** [comment]
Installation was successful with python=3.8

**Comment by jkim0731** [comment]
But now it errors with numpy.typing module not found error (could be solved by pip install dask), 

and then` ImportError: cannot import name '_get_lzma_file' from 'pandas.compat'`

**Comment by alexpiet** [comment]
Sorry you are having trouble. In `environment.yml` python is listed at `3.6.8` and SimpleITK at `1.2.0`

**Comment by alexpiet** [comment]
@jkim0731 Why are you trying to install the repo? If you just want to do analysis of the existing fits, then you can load the summary dataframes without installing the repo.

**Comment by jkim0731** [comment]
I wanted to fit new data and to try with some other conditions for GLM fitting, but I can start with just loading the results. I'll also give it a try to use the version of python and simpleITK you mentioned above. Thanks for the comments!

**Comment by jkim0731** [comment]
Tried with python=3.6.8 and pip install SimpleITK==1.2.0.
Editable mode installation says `Collecting simpleitk<3.0.0,>=2.0.2` and eventually installed 2.1.1.2
Then visual_behavior_analysis installation failed for opencv-python.

My guess is that newer version of vba requires newer python version.

**Comment by alexpiet** [comment]
Ah, I specifically do not support new versions of visual_behavior_analysis. That package doesn't have strict versioning, so I just have a note in the environment.yml file about what git commit to use. I got annoyed that VBA kept changing and I had to re-write and re-write functions, so I just dropped support for it. 

> allensdk 2.13.4, Git commit: 351850c7
> VBA 0.13.1, but meaningless. Git commit: a0b0ce5e

**Comment by jkim0731** [comment]
Seems like most of the dependencies are covered by visual_behavior_analysis and allen_sdk, except for dask.
So, by installing dask first, and then installing vba and allen_sdk, I could make visual_behavior_glm work by adding it to the path.

Error logging does not work because visual_behavior_data mongo db does not respond, but this is an issue with vba I think.
